use bofa_lib::action::Bofa;
use bofa_lib::action::check::pr::{CommentStatus, attach_marker};
use bofa_lib::config::BofaConfig;
use bofa_lib::config::credentials::{Credentials, PersonalTokenCredentials, SecretString};
use bofa_lib::config::repository::RepositoryConfig;
use bofa_lib::config::scanner::sensitive::{SensitiveScannerConfig, SensitiveScannerItem};
use bofa_lib::git::PullRequestMetadata;
use bofa_lib::git::backend::mock::MockGitBackend;
use bofa_lib::git::{ChangedFile, FileChangeStatus, IssueComment};

fn test_config() -> BofaConfig {
    BofaConfig {
        credentials: Credentials::PersonalToken(PersonalTokenCredentials {
            token: SecretString::new("$DUMMY_TOKEN"),
        }),
        repository: RepositoryConfig {
            owner: "owner".to_string(),
            repo: "repo".to_string(),
        },
        worker: Default::default(),
        scanner: Default::default(),
        template: Default::default(),
        log: Default::default(),
    }
}

fn config_with_sensitive_scanner() -> BofaConfig {
    let mut config = test_config();
    config.scanner.sensitive = SensitiveScannerConfig {
        enabled: true,
        always_report: false,
        item: indexmap::indexmap! {
            "core-repo".to_string() => SensitiveScannerItem {
                description: "Core repo".to_string(),
                paths: vec!["/path/to/repo1/**".to_string()],
                members: vec!["alice".to_string(), "bob".to_string()],
            },
            "other".to_string() => SensitiveScannerItem {
                description: "Other".to_string(),
                paths: vec!["/other/**".to_string()],
                members: vec!["carol".to_string()],
            },
        },
    };
    config
}

fn changed_file(path: &str) -> ChangedFile {
    ChangedFile {
        path: path.to_string(),
        status: FileChangeStatus::Modified,
    }
}

#[tokio::test]
async fn check_pr_returns_none_when_scanner_disabled() {
    let backend = MockGitBackend::new();
    backend.set_pull_request(|| async {
        Ok(PullRequestMetadata {
            number: 42,
            title: "Fix bug".to_string(),
            state: "closed".to_string(),
            author: "alice".to_string(),
            draft: false,
            url: "https://github.com/owner/repo/pull/42".to_string(),
        })
    });
    let bofa = Bofa::new(test_config())
        .authenticate_with(Box::new(backend))
        .await
        .unwrap();
    let output = bofa.check_pr(42).await.unwrap();
    assert!(output.body.is_none());
    assert_eq!(output.status, CommentStatus::Skipped);
    assert!(output.comment_url.is_none());
}

#[tokio::test]
async fn check_pr_propagates_backend_error() {
    let backend = MockGitBackend::new();
    backend.set_pull_request(|| async { Err(bofa_lib::git::Error::Api("boom".to_string())) });
    let bofa = Bofa::new(test_config())
        .authenticate_with(Box::new(backend))
        .await
        .unwrap();
    let err = bofa.check_pr(42).await.unwrap_err();
    assert!(matches!(
        err,
        bofa_lib::action::Error::Git(bofa_lib::git::Error::Api(_))
    ));
}

fn config_with_sensitive_scanner_always_report() -> BofaConfig {
    let mut config = config_with_sensitive_scanner();
    config.scanner.sensitive.always_report = true;
    config
}

#[tokio::test]
async fn check_pr_returns_default_empty_report_when_always_report_enabled_and_no_sensitive_files() {
    let backend = MockGitBackend::new();
    backend.set_pull_request(|| async {
        Ok(PullRequestMetadata {
            number: 42,
            title: "Fix bug".to_string(),
            state: "closed".to_string(),
            author: "dave".to_string(),
            draft: false,
            url: "https://github.com/owner/repo/pull/42".to_string(),
        })
    });
    backend.set_changed_files(|| async { Ok(vec![changed_file("/unrelated/file.txt")]) });
    let bofa = Bofa::new(config_with_sensitive_scanner_always_report())
        .authenticate_with(Box::new(backend))
        .await
        .unwrap();
    let output = bofa.check_pr(42).await.unwrap();
    assert_eq!(
        output.body.unwrap(),
        "No sensitive files found.\n\n<sub>\n\nThis comment is generated by [bofa](https://github.com/Embers-of-the-Fire/bofa), commented by @octocat.\n\n</sub>"
    );
    assert_eq!(output.status, CommentStatus::Created);
    assert!(output.comment_url.is_some());
}

#[tokio::test]
async fn check_pr_returns_custom_empty_report_when_configured() {
    let mut config = config_with_sensitive_scanner_always_report();
    config.template.scanner.sensitive.empty_report = Some("All clear.".to_string());
    let backend = MockGitBackend::new();
    backend.set_pull_request(|| async {
        Ok(PullRequestMetadata {
            number: 42,
            title: "Fix bug".to_string(),
            state: "closed".to_string(),
            author: "dave".to_string(),
            draft: false,
            url: "https://github.com/owner/repo/pull/42".to_string(),
        })
    });
    backend.set_changed_files(|| async { Ok(vec![changed_file("/unrelated/file.txt")]) });
    let bofa = Bofa::new(config)
        .authenticate_with(Box::new(backend))
        .await
        .unwrap();
    let output = bofa.check_pr(42).await.unwrap();
    assert_eq!(
        output.body.unwrap(),
        "All clear.\n\n<sub>\n\nThis comment is generated by [bofa](https://github.com/Embers-of-the-Fire/bofa), commented by @octocat.\n\n</sub>"
    );
    assert_eq!(output.status, CommentStatus::Created);
    assert!(output.comment_url.is_some());
}

#[tokio::test]
async fn check_pr_omits_footnote_when_disabled() {
    let mut config = config_with_sensitive_scanner_always_report();
    config.template.comment.footnote = Some(String::new());
    let backend = MockGitBackend::new();
    backend.set_pull_request(|| async {
        Ok(PullRequestMetadata {
            number: 42,
            title: "Fix bug".to_string(),
            state: "closed".to_string(),
            author: "dave".to_string(),
            draft: false,
            url: "https://github.com/owner/repo/pull/42".to_string(),
        })
    });
    backend.set_changed_files(|| async { Ok(vec![changed_file("/unrelated/file.txt")]) });
    let bofa = Bofa::new(config)
        .authenticate_with(Box::new(backend))
        .await
        .unwrap();
    let output = bofa.check_pr(42).await.unwrap();
    assert_eq!(output.body.unwrap(), "No sensitive files found.");
    assert_eq!(output.status, CommentStatus::Created);
    assert!(output.comment_url.is_some());
}

#[tokio::test]
async fn check_pr_posts_footnote_without_app_name_when_metadata_fails() {
    let backend = MockGitBackend::with_account_metadata(|| async {
        Err(bofa_lib::git::Error::Api("metadata boom".to_string()))
    });
    backend.set_pull_request(|| async {
        Ok(PullRequestMetadata {
            number: 42,
            title: "Fix bug".to_string(),
            state: "closed".to_string(),
            author: "dave".to_string(),
            draft: false,
            url: "https://github.com/owner/repo/pull/42".to_string(),
        })
    });
    backend.set_changed_files(|| async { Ok(vec![changed_file("/unrelated/file.txt")]) });
    let bofa = Bofa::new(config_with_sensitive_scanner_always_report())
        .authenticate_with(Box::new(backend))
        .await
        .unwrap();
    let output = bofa.check_pr(42).await.unwrap();
    assert_eq!(
        output.body.unwrap(),
        "No sensitive files found.\n\n<sub>\n\nThis comment is generated by [bofa](https://github.com/Embers-of-the-Fire/bofa).\n\n</sub>"
    );
    assert_eq!(output.status, CommentStatus::Created);
    assert!(output.comment_url.is_some());
}

#[tokio::test]
async fn check_pr_reports_sensitive_files_and_related_persons() {
    let backend = MockGitBackend::new();
    backend.set_pull_request(|| async {
        Ok(PullRequestMetadata {
            number: 42,
            title: "Fix bug".to_string(),
            state: "closed".to_string(),
            author: "dave".to_string(),
            draft: false,
            url: "https://github.com/owner/repo/pull/42".to_string(),
        })
    });
    backend.set_changed_files(|| async {
        Ok(vec![
            changed_file("/path/to/repo1/src/main.rs"),
            changed_file("/other/README.md"),
        ])
    });
    let bofa = Bofa::new(config_with_sensitive_scanner())
        .authenticate_with(Box::new(backend))
        .await
        .unwrap();
    let output = bofa.check_pr(42).await.unwrap();
    let body = output.body.unwrap();
    assert!(body.contains("Core repo"));
    assert!(body.contains("/path/to/repo1/src/main.rs"));
    assert!(body.contains("alice"));
    assert!(body.contains("bob"));
    assert!(body.contains("Other"));
    assert!(body.contains("/other/README.md"));
    assert!(body.contains("carol"));
    assert_eq!(output.status, CommentStatus::Created);
    assert!(output.comment_url.is_some());
}

#[tokio::test]
async fn check_pr_returns_none_when_no_sensitive_files_changed() {
    let backend = MockGitBackend::new();
    backend.set_changed_files(|| async { Ok(vec![changed_file("/unrelated/file.txt")]) });
    let bofa = Bofa::new(config_with_sensitive_scanner())
        .authenticate_with(Box::new(backend))
        .await
        .unwrap();
    let output = bofa.check_pr(42).await.unwrap();
    assert!(output.body.is_none());
    assert_eq!(output.status, CommentStatus::Skipped);
    assert!(output.comment_url.is_none());
}

#[tokio::test]
async fn check_pr_calls_changed_files_when_scanner_enabled() {
    use std::sync::Arc;
    use std::sync::atomic::{AtomicU32, Ordering};

    let call_count = Arc::new(AtomicU32::new(0));
    let call_count_clone = Arc::clone(&call_count);
    let backend = MockGitBackend::new();
    backend.set_changed_files(move || {
        let call_count = Arc::clone(&call_count_clone);
        async move {
            call_count.fetch_add(1, Ordering::SeqCst);
            Ok(vec![changed_file("/path/to/repo1/src/main.rs")])
        }
    });
    let bofa = Bofa::new(config_with_sensitive_scanner())
        .authenticate_with(Box::new(backend))
        .await
        .unwrap();
    bofa.check_pr(42).await.unwrap();
    assert_eq!(call_count.load(Ordering::SeqCst), 1);
}

#[tokio::test]
async fn check_pr_does_not_call_changed_files_when_scanner_disabled() {
    use std::sync::Arc;
    use std::sync::atomic::{AtomicU32, Ordering};

    let call_count = Arc::new(AtomicU32::new(0));
    let call_count_clone = Arc::clone(&call_count);
    let backend = MockGitBackend::new();
    backend.set_changed_files(move || {
        let call_count = Arc::clone(&call_count_clone);
        async move {
            call_count.fetch_add(1, Ordering::SeqCst);
            Ok(vec![changed_file("/path/to/repo1/src/main.rs")])
        }
    });
    let bofa = Bofa::new(test_config())
        .authenticate_with(Box::new(backend))
        .await
        .unwrap();
    bofa.check_pr(42).await.unwrap();
    assert_eq!(call_count.load(Ordering::SeqCst), 0);
}

#[tokio::test]
async fn check_pr_posts_comment_and_returns_url_when_enabled() {
    let backend = MockGitBackend::new();
    backend.set_pull_request(|| async {
        Ok(PullRequestMetadata {
            number: 42,
            title: "Fix bug".to_string(),
            state: "closed".to_string(),
            author: "dave".to_string(),
            draft: false,
            url: "https://github.com/owner/repo/pull/42".to_string(),
        })
    });
    backend.set_changed_files(|| async { Ok(vec![changed_file("/path/to/repo1/src/main.rs")]) });
    let bofa = Bofa::new(config_with_sensitive_scanner())
        .authenticate_with(Box::new(backend))
        .await
        .unwrap();
    let output = bofa.check_pr(42).await.unwrap();
    assert!(output.body.is_some());
    assert_eq!(output.status, CommentStatus::Created);
    assert_eq!(
        output.comment_url,
        Some("https://github.com/test/repo/pull/1#issuecomment-1".to_string())
    );
}

#[tokio::test]
async fn check_pr_does_not_post_comment_when_disabled() {
    let backend = MockGitBackend::new();
    backend.set_pull_request(|| async {
        Ok(PullRequestMetadata {
            number: 42,
            title: "Fix bug".to_string(),
            state: "closed".to_string(),
            author: "dave".to_string(),
            draft: false,
            url: "https://github.com/owner/repo/pull/42".to_string(),
        })
    });
    backend.set_changed_files(|| async { Ok(vec![changed_file("/path/to/repo1/src/main.rs")]) });
    let mut config = config_with_sensitive_scanner();
    config.worker.post_comments = false;
    let bofa = Bofa::new(config)
        .authenticate_with(Box::new(backend))
        .await
        .unwrap();
    let output = bofa.check_pr(42).await.unwrap();
    assert!(output.body.is_some());
    assert_eq!(output.status, CommentStatus::Skipped);
    assert!(output.comment_url.is_none());
}

const EMPTY_REPORT_RENDERED: &str = "No sensitive files found.\n\n<sub>\n\nThis comment is generated by [bofa](https://github.com/Embers-of-the-Fire/bofa), commented by @octocat.\n\n</sub>";

fn marked_comment(id: u64, author: &str, rendered: &str) -> IssueComment {
    IssueComment {
        id,
        body: attach_marker(rendered),
        author_login: author.to_string(),
        url: format!("https://github.com/owner/repo/pull/42#issuecomment-{id}"),
    }
}

fn always_report_backend() -> MockGitBackend {
    let backend = MockGitBackend::new();
    backend.set_pull_request(|| async {
        Ok(PullRequestMetadata {
            number: 42,
            title: "Fix bug".to_string(),
            state: "closed".to_string(),
            author: "dave".to_string(),
            draft: false,
            url: "https://github.com/owner/repo/pull/42".to_string(),
        })
    });
    backend.set_changed_files(|| async { Ok(vec![changed_file("/unrelated/file.txt")]) });
    backend
}

#[tokio::test]
async fn check_pr_skips_update_when_comment_is_unchanged() {
    let backend = always_report_backend();
    backend.set_list_comments(|| async {
        Ok(vec![marked_comment(7, "octocat", EMPTY_REPORT_RENDERED)])
    });
    let bofa = Bofa::new(config_with_sensitive_scanner_always_report())
        .authenticate_with(Box::new(backend))
        .await
        .unwrap();
    let output = bofa.check_pr(42).await.unwrap();
    assert_eq!(output.status, CommentStatus::Unchanged);
    assert_eq!(
        output.comment_url,
        Some("https://github.com/owner/repo/pull/42#issuecomment-7".to_string())
    );
}

#[tokio::test]
async fn check_pr_updates_existing_marked_comment_when_content_changes() {
    let backend = always_report_backend();
    backend.set_list_comments(|| async { Ok(vec![marked_comment(7, "octocat", "stale report")]) });
    backend.set_update_comment(|| async {
        Ok("https://github.com/owner/repo/pull/42#issuecomment-7".to_string())
    });
    let bofa = Bofa::new(config_with_sensitive_scanner_always_report())
        .authenticate_with(Box::new(backend))
        .await
        .unwrap();
    let output = bofa.check_pr(42).await.unwrap();
    assert_eq!(output.status, CommentStatus::Updated);
    assert_eq!(
        output.comment_url,
        Some("https://github.com/owner/repo/pull/42#issuecomment-7".to_string())
    );
}

#[tokio::test]
async fn check_pr_creates_new_comment_when_no_marked_comment_exists() {
    let backend = always_report_backend();
    backend.set_list_comments(|| async {
        Ok(vec![IssueComment {
            id: 3,
            body: "a human comment".to_string(),
            author_login: "octocat".to_string(),
            url: "https://github.com/owner/repo/pull/42#issuecomment-3".to_string(),
        }])
    });
    let bofa = Bofa::new(config_with_sensitive_scanner_always_report())
        .authenticate_with(Box::new(backend))
        .await
        .unwrap();
    let output = bofa.check_pr(42).await.unwrap();
    assert_eq!(output.status, CommentStatus::Created);
    assert_eq!(
        output.comment_url,
        Some("https://github.com/test/repo/pull/1#issuecomment-1".to_string())
    );
}
